import Image from "next/image";
import Link from "next/link";
import { ArrowRight, HeartHandshake, ShieldCheck, Sparkles } from "lucide-react";
import { latestNews, pillars, stats } from "@/lib/content";
import { NewsCard } from "@/components/news-card";
import { PixDonation } from "@/components/pix-donation";

export default function Home() {
  return <main>
    <section className="bg-teal-deep text-white"><div className="container-page grid min-h-[650px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
      <div className="max-w-2xl"><p className="eyebrow !text-lime">Projeto Soldados Valorosos · Desde 2018</p><h1 className="display mt-5 text-5xl leading-[.98] sm:text-6xl lg:text-7xl">Ninguém deveria enfrentar a fome sozinho.</h1><p className="mt-7 max-w-xl text-base leading-8 text-white/80">Toda quinta-feira, uma rede de pessoas transforma alimento, roupa e esperança em cuidado para quem vive nas ruas da Baixada Santista.</p><Link className="button-primary focus-ring mt-9 !bg-lime !text-ink hover:!bg-white" href="#historia">Conheça nossa história <ArrowRight size={17} /></Link></div>
      <div className="relative h-[430px] overflow-hidden sm:h-[500px]"><Image priority fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover object-[50%_24%]" alt="Alexandre, fundador do Projeto Soldados Valorosos, durante o preparo das ações" src="/images/alexandre-fundador.png"/><div className="absolute bottom-0 left-0 max-w-[85%] bg-magenta px-6 py-5 text-sm font-bold">Uma história de recomeço que hoje ajuda outras histórias a recomeçarem.</div></div>
    </div></section>

    <section id="historia" className="container-page grid gap-12 py-24 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="relative min-h-[460px] overflow-hidden"><Image fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" alt="Voluntários do Soldados Valorosos preparando marmitas" src="/images/preparo-marmitas.png"/><div className="absolute bottom-0 right-0 max-w-[82%] bg-paper p-6 text-ink sm:p-8"><p className="eyebrow">O começo</p><p className="display mt-3 text-2xl leading-tight">“Um sonho que nasceu da vontade de não deixar ninguém para trás.”</p></div></div><div className="max-w-2xl"><p className="eyebrow">A história de Alexandre e Neide</p><h2 className="display mt-4 text-4xl leading-tight sm:text-5xl">Antes de ajudar outras pessoas a saírem das ruas, Alexandre precisou encontrar o caminho de volta para si.</h2><p className="mt-7 text-lg leading-8 text-ink/75">Alexandre viveu a realidade das ruas. Ao lado de sua esposa, Neide, transformou essa experiência em uma missão: estar perto de quem ainda enfrenta a fome, a dependência química, o abandono e a falta de um lugar para recomeçar.</p><p className="mt-5 leading-8 text-ink/65">Desde 2018, o Projeto Soldados Valorosos leva alimentos, roupas e produtos de higiene a moradores de rua e famílias de baixa renda da Baixada Santista. O que começou como o sonho de um casal hoje é uma corrente de cuidado.</p></div></section>

    <section className="border-y border-ink/10 bg-white"><div className="container-page py-10"><p className="eyebrow">Toda quinta-feira</p><div className="mt-5 grid divide-y divide-ink/10 md:grid-cols-3 md:divide-x md:divide-y-0">{stats.map((stat) => <div key={stat.label} className="py-6 md:px-10 first:md:pl-0"><p className="display text-5xl text-teal-deep">{stat.value}</p><p className="mt-2 text-sm font-bold text-ink/65">{stat.label}</p></div>)}</div></div></section>

    <section className="container-page py-24"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow">Pequenos gestos, grandes respiros</p><h2 className="display mt-4 text-4xl sm:text-5xl">Cuidado também é não deixar ninguém invisível.</h2></div><p className="max-w-xl leading-8 text-ink/65">Uma marmita não resolve tudo. Mas pode ser o começo de uma conversa, de um sorriso e de uma nova chance de seguir em frente.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{pillars.map((pillar, index) => { const Icon = [HeartHandshake, ShieldCheck, Sparkles][index]; return <article className="border border-ink/10 bg-white p-7" key={pillar.title}><Icon className="text-magenta" size={28}/><h3 className="mt-8 text-lg font-extrabold">{pillar.title}</h3><p className="mt-3 leading-7 text-sm text-ink/65">{pillar.description}</p></article> })}</div></section>

    <section className="bg-[#edf4ee]"><div className="container-page grid gap-5 py-24 lg:grid-cols-[1.18fr_.82fr]"><div className="relative min-h-[500px] overflow-hidden"><Image fill sizes="(max-width: 1024px) 100vw, 58vw" className="object-cover" alt="Voluntárias preparam marmitas para as ações do projeto" src="/images/voluntarios-cozinha.png"/></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1"><div className="relative min-h-[240px] overflow-hidden"><Image fill sizes="(max-width: 640px) 100vw, 30vw" className="object-cover" alt="Voluntários nos bastidores da preparação" src="/images/bastidores-cozinha.png"/></div><div className="bg-magenta p-8 text-white sm:p-10"><p className="eyebrow !text-lime">Feito por muitas mãos</p><h2 className="display mt-4 text-4xl leading-tight">O projeto dá certo porque ninguém faz isso sozinho.</h2><p className="mt-5 leading-8 text-white/80">Cozinheiros, motoristas, distribuidores, voluntários e doadores fazem cada quinta-feira acontecer.</p></div></div></div></section>

    <section className="bg-[#edf4ee]"><div className="container-page py-24"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Acontece por aqui</p><h2 className="display mt-4 text-4xl sm:text-5xl">Últimas notícias</h2></div><Link href="/noticias" className="button-secondary focus-ring">Ver todas <ArrowRight size={16}/></Link></div>{latestNews.length ? <div className="mt-12 grid gap-7 md:grid-cols-3">{latestNews.map((news) => <NewsCard key={news.slug} news={news}/>)}</div> : <div className="mt-10 border-l-4 border-lime bg-white p-8"><p className="text-lg font-extrabold">As notícias oficiais chegam em breve.</p><p className="mt-2 text-sm leading-7 text-ink/65">Enquanto isso, acompanhe as ações do projeto pelo Instagram.</p><a className="focus-ring mt-5 inline-block text-sm font-bold text-teal underline" href="https://www.instagram.com/sejasoldado/" target="_blank" rel="noreferrer">Ver Instagram do projeto</a></div>}</div></section>

    <section className="bg-magenta text-white"><div className="container-page grid gap-10 py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="eyebrow !text-lime">Faça parte</p><h2 className="display mt-3 text-4xl sm:text-5xl">O que sustenta esse projeto são as pessoas em conjunto.</h2><p className="mt-5 max-w-xl leading-8 text-white/80">Quem doa, quem cozinha, quem dirige, quem distribui e quem escolhe acreditar. Toda ajuda vira presença na vida de alguém.</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col lg:items-start"><a className="button-primary focus-ring !bg-white !text-ink hover:!bg-lime" href="https://api.whatsapp.com/send?phone=5513981529639&text=Olá!%20Quero%20ser%20voluntário(a)%20do%20Projeto%20Soldados%20Valorosos." target="_blank" rel="noreferrer">Quero ser voluntário <ArrowRight size={17}/></a><PixDonation/></div></div></section>
  </main>;
}
