import Image from "next/image";
import Link from "next/link";
import { ArrowRight, HeartHandshake, ShieldCheck, Sparkles } from "lucide-react";
import { latestNews, pillars, stats } from "@/lib/content";
import { NewsCard } from "@/components/news-card";

export default function Home() {
  return <main>
    <section className="bg-teal-deep text-white"><div className="container-page grid min-h-[650px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
      <div className="max-w-2xl"><p className="eyebrow !text-lime">Projeto Soldados Valorosos</p><h1 className="display mt-5 text-5xl leading-[.98] sm:text-6xl lg:text-7xl">Ninguém deveria enfrentar a fome sozinho.</h1><p className="mt-7 max-w-xl text-base leading-8 text-white/80">Toda quinta-feira, levamos alimento, roupa e esperança a quem vive nas ruas da Baixada Santista.</p><Link className="button-primary focus-ring mt-9 !bg-lime !text-ink hover:!bg-white" href="#conheca">Conheça nossa história <ArrowRight size={17} /></Link></div>
      <div className="relative h-[390px] overflow-hidden sm:h-[470px]"><Image priority fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" alt="Pessoas reunidas em uma atividade comunitária" src="https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1200&q=85"/><div className="absolute bottom-0 left-0 max-w-[85%] bg-magenta px-6 py-5 text-sm font-bold">Porque uma marmita também pode dizer: você não está sozinho.</div></div>
    </div></section>

    <section id="conheca" className="container-page grid gap-12 py-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Quem somos</p><h2 className="display mt-4 text-4xl leading-tight sm:text-5xl">Não é só sobre entregar uma marmita.</h2></div><div className="max-w-2xl"><p className="text-lg leading-8 text-ink/75">É sobre olhar no olho. É sobre lembrar alguém de que a sua história ainda importa.</p><p className="mt-5 leading-8 text-ink/65">Somos o nascimento de um sonho e a dedicação de amor de pessoas por outras pessoas. Levamos alimentos, roupas e esperança a moradores de rua da Baixada Santista, além de cestas básicas para famílias carentes.</p></div></section>

    <section className="border-y border-ink/10 bg-white"><div className="container-page py-10"><p className="eyebrow">Toda quinta-feira</p><div className="mt-5 grid divide-y divide-ink/10 md:grid-cols-3 md:divide-x md:divide-y-0">{stats.map((stat) => <div key={stat.label} className="py-6 md:px-10 first:md:pl-0"><p className="display text-5xl text-teal-deep">{stat.value}</p><p className="mt-2 text-sm font-bold text-ink/65">{stat.label}</p></div>)}</div></div></section>

    <section className="container-page py-24"><div className="max-w-2xl"><p className="eyebrow">Pequenos gestos, grandes respiros</p><h2 className="display mt-4 text-4xl sm:text-5xl">Cuidado também é não deixar ninguém invisível.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{pillars.map((pillar, index) => { const Icon = [HeartHandshake, ShieldCheck, Sparkles][index]; return <article className="border border-ink/10 bg-white p-7" key={pillar.title}><Icon className="text-magenta" size={28}/><h3 className="mt-8 text-lg font-extrabold">{pillar.title}</h3><p className="mt-3 leading-7 text-sm text-ink/65">{pillar.description}</p></article> })}</div></section>

    <section className="bg-[#edf4ee]"><div className="container-page py-24"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Acontece por aqui</p><h2 className="display mt-4 text-4xl sm:text-5xl">Últimas notícias</h2></div><Link href="/noticias" className="button-secondary focus-ring">Ver todas <ArrowRight size={16}/></Link></div>{latestNews.length ? <div className="mt-12 grid gap-7 md:grid-cols-3">{latestNews.map((news) => <NewsCard key={news.slug} news={news}/>)}</div> : <div className="mt-10 border-l-4 border-lime bg-white p-8"><p className="text-lg font-extrabold">As notícias oficiais chegam em breve.</p><p className="mt-2 text-sm leading-7 text-ink/65">Enquanto isso, acompanhe as ações do projeto pelo Instagram.</p><a className="focus-ring mt-5 inline-block text-sm font-bold text-teal underline" href="https://www.instagram.com/sejasoldado/" target="_blank" rel="noreferrer">Ver Instagram do projeto</a></div>}</div></section>

    <section className="bg-magenta text-white"><div className="container-page flex flex-col items-start justify-between gap-8 py-16 md:flex-row md:items-center"><div><p className="eyebrow !text-lime">Faça parte</p><h2 className="display mt-3 text-4xl sm:text-5xl">Um gesto simples pode acender esperança.</h2></div><Link href="/seja-parceiro" className="button-primary focus-ring !bg-white !text-ink hover:!bg-lime">Seja parte disso <ArrowRight size={17}/></Link></div></section>
  </main>;
}
