import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { notFound } from "next/navigation";
import { getPublishedAction } from "@/lib/cms";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const item = await getPublishedAction((await params).slug); return item ? { title: item.title, description: item.excerpt, openGraph: item.cover_image_url ? { images: [item.cover_image_url] } : undefined } : {}; }
export default async function ActionPage({ params }: { params: Promise<{ slug: string }> }) { const item = await getPublishedAction((await params).slug); if (!item) notFound(); const image = item.cover_image_url ?? item.action_images[0]?.url; const date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "long", timeZone: "UTC" }).format(new Date(`${item.action_date}T12:00:00Z`)); return <main><article><header className="container-page mx-auto max-w-4xl py-14 sm:py-20"><Link className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-teal hover:underline" href="/noticias"><ArrowLeft size={16}/> Todas as ações</Link><p className="eyebrow mt-10">{date}{item.action_time && <span className="ml-2 text-ink/50">{item.action_time}</span>}</p><h1 className="display mt-5 text-5xl leading-[1.02] sm:text-6xl">{item.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-ink/70">{item.excerpt}</p></header>{image && <div className="container-page"><div className="relative mx-auto aspect-[1.8] max-w-5xl overflow-hidden"><Image src={image} fill sizes="(max-width: 1024px) 100vw, 80vw" className="object-cover" alt={item.action_images[0]?.alt ?? item.title}/></div></div>}<div className="container-page mx-auto max-w-3xl py-14 text-lg leading-9 text-ink/75">{item.content.split("\n").filter(Boolean).map((paragraph) => <p className="mb-7" key={paragraph}>{paragraph}</p>)}</div>{item.action_images.length > 1 && <div className="container-page mx-auto grid max-w-5xl gap-4 pb-20 sm:grid-cols-2">{item.action_images.slice(1).map((photo) => <div className="relative aspect-[1.3] overflow-hidden" key={photo.id}><Image src={photo.url} alt={photo.alt ?? item.title} fill className="object-cover"/></div>)}</div>}</article></main>; }
